CREATE TABLE LUSI_ESUBMISSION_JOBS (
    JOB_ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    STUDENTUSERNAME VARCHAR(64) NOT NULL,
    YEARIDENTITY CHAR(6) NOT NULL,
    WORKIDENTITY VARCHAR(36) NOT NULL,
    ESUBMISSIONTIME MEDIUMINT NOT NULL,
    PRIMARY KEY(JOB_ID),
    UNIQUE INDEX(STUDENTUSERNAME,YEARIDENTITY,WORKIDENTITY)
);
